services:
  - type: web
    name: multi-agent-ai-analyst
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python seed_db.py && python ingest.py
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: GEMINI_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: LANGFUSE_SECRET_KEY
        sync: false
      - key: LANGFUSE_PUBLIC_KEY
        sync: false
      - key: LANGFUSE_HOST
        value: https://cloud.langfuse.com
